### ISSUE TITLE
RuntimeError: Could not run 'aten::add_.Tensor' with arguments from the 'QuantizedCPU' backend.

### ISSUE THREAD

**Issue by TaeSeokL** [leimao/PyTorch-Quantization-Aware-Training#6]
Hi thanks for the great code. 
But i ran this code there is little problem.

In your code
   _, int8_eval_accuracy = evaluate_model(model=quantized_jit_model,
                                           test_loader= val_loader,
                                           device=cpu_device,
                                           criterion=None)

at this line, i see RuntimeError: Could not run 'aten::add_.Tensor' with arguments from the 'QuantizedCPU' backend. this problem.
Is there something that i forgot ?

**Comment by leimao** [comment]
Please try using the Docker container, as PyTorch changes the API and implementations from time to time.
